name: build
on:
  push:
    tags:
      - v*
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Visual Studio Build Tools
        uses: microsoft/setup-msbuild@v2
      - name: Make PyInstaller recompile bootloader
        run: |
          echo "PYINSTALLER_COMPILE_BOOTLOADER=1" >> $env:GITHUB_ENV
      - name: Install PyInstaller
        run: PYINSTALLER_COMPILE_BOOTLOADER=1 pip install -U git+https://github.com/pyinstaller/pyinstaller.git@v6.16.0
      - name: Install Stream Deck SDK
        run: pip install "streamdeck-sdk[dev]"
      - name: Install requirements
        run: pip install -r nl.koenvh.screendeck.sdPlugin/code/requirements.txt
      - name: Build plug-in
        run: .\build.cmd
      - name: Get subfolder name
        shell: pwsh
        run: |
          $subfolder = Get-ChildItem -Path "releases" -Directory | Select-Object -ExpandProperty Name
          echo "SUBFOLDER_NAME=$subfolder" >> $env:GITHUB_ENV
      - name: Make release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: "releases/${{ env.SUBFOLDER_NAME }}/nl.koenvh.screendeck.streamDeckPlugin"
