name: build
on:
  push:
    tags:
      - v*
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Checkout PyInstaller source
        uses: actions/checkout@v4
        with:
          repository: pyinstaller/pyinstaller
          path: pyinstaller
          ref: v6.14.2
      - name: Install PyInstaller build dependencies
        run: |
          pip install --upgrade pip wheel setuptools
          pip install pypiwin32 pefile pywin32-ctypes
      - name: Make PyInstaller recompile bootloader
        run: |
          echo "PYINSTALLER_COMPILE_BOOTLOADER=1" >> $env:GITHUB_ENV
      - name: Install Visual Studio Build Tools
        uses: microsoft/setup-msbuild@v2
      - name: Build bootloader
        working-directory: pyinstaller/bootloader
        run: |
          python ./waf all
      - name: Install PyInstaller (with custom bootloader)
        working-directory: pyinstaller
        run: |
          python setup.py install

      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Stream Deck SDK
        run: pip install "streamdeck-sdk[dev]"
      - name: Install requirements
        run: pip install -r nl.koenvh.screendeck.sdPlugin/code/requirements.txt
      - name: Build plug-in
        run: .\build.cmd
      - name: Get subfolder name
        shell: pwsh
        run: |
          $subfolder = Get-ChildItem -Path "releases" -Directory | Select-Object -ExpandProperty Name
          echo "SUBFOLDER_NAME=$subfolder" >> $env:GITHUB_ENV
      - name: Make release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: "releases/${{ env.SUBFOLDER_NAME }}/nl.koenvh.screendeck.streamDeckPlugin"
