name: build
on:
  push:
    tags:
      - v*
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Unzip Python Embedded
        run: Expand-Archive -Path nl.koenvh.screendeck.sdPlugin\python312-embedded.zip -DestinationPath nl.koenvh.screendeck.sdPlugin\python312-embedded
      - name: Remove Python Embedded zip
        run: Remove-Item -Path nl.koenvh.screendeck.sdPlugin\python312-embedded.zip
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Stream Deck SDK
        run: pip install "streamdeck-sdk[dev]"
      - name: Install requirements
        run: pip install -r nl.koenvh.screendeck.sdPlugin/code/requirements.txt
      - name: Build plug-in
        run: .\build.cmd
      - name: Get subfolder name
        shell: pwsh
        run: |
          $subfolder = Get-ChildItem -Path "releases" -Directory | Select-Object -ExpandProperty Name
          echo "SUBFOLDER_NAME=$subfolder" >> $env:GITHUB_ENV
      - name: Make release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: "releases/${{ env.SUBFOLDER_NAME }}/nl.koenvh.screendeck.streamDeckPlugin"
